### ISSUE TITLE
F-secure false positive

### ISSUE THREAD

**Issue by viljoviitanen** [stuartleeks/wsl-clock#2]
FYI,

F-secure computer protection (not my choice, employer policy...) automatically detected wsl-clock.exe from https://github.com/stuartleeks/wsl-clock/releases/tag/v0.1.207519386 as a threat. I've reported it to f-secure as "false positive". sha256 of the actual binary: aa5333586c4369728d0ee3e196d7460f8a2ec4d3015a64054c8a1945cb49a80c wsl-clock.exe

Details of the scan from f-secure on my computer:

Scan report - F-Secure Computer Protection
Saturday, 12 September 2020 13.02.48 - 13.02.48
Scan type: Scan for viruses

Targets:
C:\Users\vviitanen\Downloads\wsl-clock_windows_amd64\wsl-clock.exe 
Exclusions:
C:\Users\vviitanen\Downloads\wsl-clock_windows_amd64\wsl-clock.exe 
Results
Harmful items found: 1 
Items scanned: 1 
Harmful items:
HEUR/APC 
C:\Users\vviitanen\Downloads\wsl-clock_windows_amd64\wsl-clock.exe 
Version information
Scanning engines:
F-Secure Capricorn: 18.0.713, 2020-09-12 
F-Secure Hydra: 6.0.235, 2020-09-10 
F-Secure Lynx: 2.4.6 
F-Secure Online: 18.0.101 
F-Secure USS: 6.0.35, 2020-04-14 
F-Secure Virgo Detection: 18.0.101

**Comment by stuartleeks** [comment]
Oh, interesting! Thanks for reporting and flagging as a false positive 😃

**Comment by viljoviitanen** [comment]
To follow up, I got a response from f-secure:

> Thank you for your submission.
> 
> Our analysis has found that the file you submitted is clean.
> 
> We have identified the issue as a False Positive, which will be resolved automatically via F-Secure's Security Cloud.

out of curiosity, I submitted the file to virustotal, which resulted in one av product to detect the file as malicious https://www.virustotal.com/gui/file/aa5333586c4369728d0ee3e196d7460f8a2ec4d3015a64054c8a1945cb49a80c/detection
