### ISSUE TITLE
Update README.md to mention compilation is required

### ISSUE THREAD

**Issue by HolisticDeveloper** [stuartleeks/wsl-clock#3]
A minor detail, but README.md should mention that go is required and that the code will need to be built using `go build`. Since I'm not a go developer, I didn't realize it at first. It was easy enough to do it once I figured that out though. 😄

**Comment by stuartleeks** [comment]
Thanks for raising this. I've added [compiled releases](https://github.com/stuartleeks/wsl-clock/releases) but now realise that I hadn't updated the README to point to them - thanks!

**Comment by HolisticDeveloper** [comment]
Ah, I hadn't noticed the releases -- did GitHub change its UI recently for where those are listed? I thought they used to be across the top nav under Code. I do see them now on the right hand side.
