### ISSUE TITLE
Windows Defender identifies `wsl-clock` as a threat

### ISSUE THREAD

**Issue by simonratner** [stuartleeks/wsl-clock#4]
![image](https://user-images.githubusercontent.com/667283/94203669-acfacb00-fe74-11ea-8682-11e88d3f0b2b.png)

**Comment by stuartleeks** [comment]
I tested a release yesterday and noticed this issue, but it seemed to have resolved itself later in the day. I have just found a form to submit it to the Microsoft Defender team as a false positive so will see what that review comes back with. Thanks for reporting it.

**Comment by simonratner** [comment]
It does seem to have corrected itself after updating the Defender signatures - but not before removing the scheduled task. Something to keep in mind: the task has to be recreated.
